name: Paso 1, Crea tu primer workflow file

# This step triggers after TBD-step-1-event-desc
# This step sets STEP to 2
# This step closes <details id=1> and opens <details id=2>

# This will run every time we TBD-step-1-event-desc
# Reference https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  push:
    branches:
      - aprendiendo-github-actions

# Reference https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  # Need `contents: read` to checkout the repository
  # Need `contents: write` to update the step metadata
  contents: write

jobs:
  # Get the current step from .github/script/STEP so we can
  # limit running the main job when the learner is on the same step.
  obtener_paso_actual:
    name: Verificar paso actual
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: obtener_paso
        run: |
          echo "paso_actual=$(cat ./.github/script/STEP)" >> $GITHUB_OUTPUT
    outputs:
      paso_actual: ${{ steps.obtener_paso.outputs.paso_actual }}

  crear_hola_mundo:
    name: Crear Hola Mundo
    needs: obtener_paso_actual

    # We will only run this action when:
    # 1. This repository isn't the template repository
    # 2. The STEP is currently 1
    # Reference https://docs.github.com/en/actions/learn-github-actions/contexts
    # Reference https://docs.github.com/en/actions/learn-github-actions/expressions
    if: >-
      ${{ !github.event.repository.is_template
          && needs.obtener_paso_actual.outputs.paso_actual == 1 }}

    # We'll run Ubuntu for performance instead of Mac or Windows
    runs-on: ubuntu-latest

    steps:
      # We'll need to check out the repository so that we can edit the README
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Let's get all the branches

      # Verify the learner added the file contents
      - name: Verificar contenido del nuevo workflow
        run: ./.github/script/check-file.sh
        env:
          FILE: ".github/workflows/hola-mundo.yml"
          SEARCH: "name:"

      # Update README to close <details id=1> and open <details id=2>
      # and set STEP to '2'
      - name: Actualizar a paso 2
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 1
          to_step: 2
          branch_name: aprendiendo-github-actions
